### ISSUE TITLE
Can I compile it on Windows instead of Linux？

### ISSUE THREAD

**Issue by SenkiTK** [joncampbell123/composite-video-simulator#6]
I'm really desire to know...and if I can,could you plz tell me how to compile it as an extra lib? =(

**Comment by joncampbell123** [comment]
Yes.

The source code is maintained so that it can compile on Linux, Windows, and Mac OS X as well as a Win32 binary that can run on MS-DOS through the HX DOS extender.

For Windows, you can either compile with MinGW or with Visual Studio 2017 community edition. sln/vcproj files are maintained in the vs2015 directory.
